services:
  huawei-solar-to-influx:
    build: ./
    container_name: huawei-solar-to-influx
    networks:
      - solar-monitor
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
    environment:
      - MODBUS_ADDR=${MODBUS_ADDR}
      - MODBUS_TIMEOUT_SECONDS=${MODBUS_TIMEOUT_SECONDS}
      - MODBUS_RECONNECT_WAIT_SECONDS=${MODBUS_RECONNECT_WAIT_SECONDS}
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_DB=${INFLUX_DB}
      - INFLUX_DEVICE_TAG=${INFLUX_DEVICE_TAG}
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT}
      - APP_POLL_INTERVAL_SECONDS=${APP_POLL_INTERVAL_SECONDS}
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - solar-monitor
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - solar-monitor
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
networks:
  solar-monitor:
    driver: bridge
